# This file should only be edited from the template
name: Classroom Repo Init from Template

on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read
  issues: write

jobs:
  mainline:
    name: autog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The key is" \\${{ github.sha }}
