# This file should only be edited from the template
name: Classroom Repo Init from Template

on:
  push:
    branches:
      - '**'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  checks: write
  actions: write
  contents: read

jobs:
  mainline:
    name: autog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo "The key is" \\${{ github.sha }}
      - run: echo "The job was triggered by commit:" ${GITHUB_SHA::7}
      
  verify_issue:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/heads/issue/')
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Get issue details
      id: issue_details
      uses: octokit/request-action@v2.x
      with:
          route: GET /repos/${{ github.repository }}/issues/${{ github.ref }}
          headers: |
            Authorization: ${{ secrets.GITHUB_TOKEN }}
            Accept: application/vnd.github.v3+json

    - name: Print issue details
      run: |
          echo "Issue title: ${{ steps.issue_details.outputs.data.title }}"
          echo "Issue body: ${{ steps.issue_details.outputs.data.body }}"
          echo "Issue author: ${{ steps.issue_details.outputs.data.user.login }}"
    
    - name: Merge issue branch
      run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout master
          git merge --no-commit --no-ff "${{ github.ref }}"
          if git diff --name-only --diff-filter=U | grep -q .
          then
            echo "Merge conflict detected"
            git merge --abort
            exit 1
          fi
          git merge --abort

